[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"
[[plugins]]
package = "/apps/docs/plugins/angular-netlify-adapter"
