const nextEslintConfig = require('./eslint.next.config');

// 🚨 DO NOT EDIT THIS FILE MANUALLY! 🚨
// Run `pnpm eslint-next/nx` to update or remove this file if all rules pass.
// Add new rules globally to the `eslint.config.js` or locally to the `eslint.next.config.js` file.
// For details, refer to: tools/scripts/eslint-next/README.md
module.exports = [
  ...nextEslintConfig,
  {
    files: ['**/*'],
    rules: {
      // ❌ Errors: 3
      '@typescript-eslint/no-extraneous-class': 'off', // ❌ 2 errors
      'import/named': 'off', // ❌ 2 errors
      '@angular-eslint/use-component-view-encapsulation': 'off', // ❌ 1 error
      // ⚠️ Warnings: 1
      '@angular-eslint/template/prefer-self-closing-tags': 'off', // ⚠️ 3 warnings 🛠️
      '@angular-eslint/prefer-on-push-component-change-detection': 'off', // ⚠️ 2 warnings 🛠️
      '@angular-eslint/component-max-inline-declarations': 'off', // ⚠️ 1 warnings 🛠️
      'max-lines': 'off', // ⚠️ 1 warnings 🛠️
    },
  },
];
