const nextEslintConfig = require('./eslint.next.config');

// 🚨 DO NOT EDIT THIS FILE MANUALLY! 🚨
// Run `pnpm eslint-migration-plan` to update or remove this file if all rules pass.
// For details, refer to: tools/scripts/eslint-migration/README.md
module.exports = [
  ...nextEslintConfig,
  {
    files: ['**/*'],
    rules: {
      // ⚠️ Warnings: 1
      '@typescript-eslint/no-explicit-any': 'off', // ⚠️ 1 warning
    },
  },
];