const nextEslintConfig = require('./eslint.next.config');

// 🚨 DO NOT EDIT THIS FILE MANUALLY! 🚨
// Run `pnpm eslint-migration-plan` to update or remove this file if all rules pass.
// For details, refer to: tools/scripts/eslint-migration/README.md
module.exports = [
  ...nextEslintConfig,
  {
    files: ['**/*'],
    rules: {
      // ❌ Errors: 1
      'no-var': 'off', // ❌ 2 errors 🛠️
      // ⚠️ Warnings: 1
      '@typescript-eslint/no-non-null-assertion': 'off', // ⚠️ 3 warnings
    },
  },
];