const nextEslintConfig = require('./eslint.next.config');

// 🚨 DO NOT EDIT THIS FILE MANUALLY! 🚨
// Run `pnpm eslint-next/nx` to update or remove this file if all rules pass.
// Add new rules globally to the `eslint.config.js` or locally to the `eslint.next.config.js` file.
// For details, refer to: tools/scripts/eslint-next/README.md
module.exports = [
  ...nextEslintConfig,
  {
    files: ['**/*'],
    rules: {
      // ❌ Errors: 4
      'import/no-unresolved': 'off', // ❌ 4 errors
      '@typescript-eslint/no-non-null-assertion': 'off', // ❌ 3 errors
      '@typescript-eslint/no-require-imports': 'off', // ❌ 1 error
      'import/no-commonjs': 'off', // ❌ 1 error
      // ⚠️ Warnings: 5
      'arrow-body-style': 'off', // ⚠️ 1 warning 🛠️
      'object-shorthand': 'off', // ⚠️ 1 warning 🛠️
      'max-lines-per-function': 'off', // ⚠️ 3 warnings
      '@typescript-eslint/no-magic-numbers': 'off', // ⚠️ 1 warning
      'import/no-named-as-default': 'off', // ⚠️ 1 warning
    },
  },
];
