const nextEslintConfig = require('./eslint.next.config');

// 🚨 DO NOT EDIT THIS FILE MANUALLY! 🚨
// Run `pnpm eslint-next/nx` to update or remove this file if all rules pass.
// Add new rules globally to the `eslint.config.js` or locally to the `eslint.next.config.js` file.
// For details, refer to: tools/scripts/eslint-next/README.md
module.exports = [
  ...nextEslintConfig,
  {
    files: ['**/*'],
    rules: {
      // ❌ Errors: 13
      'no-param-reassign': 'off', // ❌ 13 errors
      'import/no-unresolved': 'off', // ❌ 5 errors
      '@typescript-eslint/no-unused-vars': 'off', // ❌ 3 errors
      '@typescript-eslint/no-non-null-assertion': 'off', // ❌ 2 errors
      'sonarjs/no-dead-store': 'off', // ❌ 2 errors
      '@typescript-eslint/no-explicit-any': 'off', // ❌ 1 error
      '@typescript-eslint/no-require-imports': 'off', // ❌ 1 error
      'import/namespace': 'off', // ❌ 1 error
      'import/no-commonjs': 'off', // ❌ 1 error
      'sonarjs/function-return-type': 'off', // ❌ 1 error
      'sonarjs/no-nested-functions': 'off', // ❌ 1 error
      'sonarjs/no-unused-vars': 'off', // ❌ 1 error
      'sonarjs/x-powered-by': 'off', // ❌ 1 error
      // ⚠️ Warnings: 9
      complexity: ['error', 25], // ⚠️ 1 warnings 🛠️
      '@typescript-eslint/consistent-type-definitions': 'off', // ⚠️ 3 warnings 🛠️
      'vitest/prefer-to-be': 'off', // ⚠️ 2 warnings 🛠️
      '@typescript-eslint/no-import-type-side-effects': 'off', // ⚠️ 1 warning 🛠️
      'max-lines-per-function': 'off', // ⚠️ 6 warnings
      '@typescript-eslint/no-shadow': 'off', // ⚠️ 4 warnings
      '@typescript-eslint/no-magic-numbers': 'off', // ⚠️ 3 warnings
      'sonarjs/todo-tag': 'off', // ⚠️ 2 warnings
      'no-console': 'off', // ⚠️ 1 warning
    },
  },
];
