const nextEslintConfig = require('./eslint.next.config');

// 🚨 DO NOT EDIT THIS FILE MANUALLY! 🚨
// Run `pnpm eslint-next/nx` to update or remove this file if all rules pass.
// Add new rules globally to the `eslint.config.js` or locally to the `eslint.next.config.js` file.
// For details, refer to: tools/scripts/eslint-next/README.md
module.exports = [
  ...nextEslintConfig,
  {
    files: ['**/*'],
    rules: {
      // ❌ Errors: 2
      'import/no-unresolved': 'off', // ❌ 15 errors
      'import/named': 'off', // ❌ 3 errors
      // ⚠️ Warnings: 1
      'max-lines': 'off', // ⚠️ 1 warning
    },
  },
];
