import { RuleViolations, sortByFixable } from './utils';

const comments = `// 🚨 DO NOT EDIT THIS FILE MANUALLY! 🚨
// Run \`pnpm eslint-next/nx\` to update or remove this file if all rules pass.
// Add new rules globally to the \`eslint.config.js\` or locally to the \`eslint.next.config.js\` file.
// For details, refer to: tools/scripts/eslint-next/README.md`;
const targetEslintRc = (
  module: 'commonjs' | 'cjs' | 'mjs' | 'module' | 'esm' = 'commonjs'
) =>
  module === 'esm' || module === 'mjs'
    ? `
import nextEslintConfig from './eslint.next.config';

${comments}
export default [
  ...nextEslintConfig,
  <RULES>
];

`
    : `
const nextEslintConfig = require('./eslint.next.config');

${comments}
module.exports = [
  ...nextEslintConfig,
  <RULES>
];

`;

const DEFAULT_INDENT_LEVEL = 6;

export function formatRules(
  rules: Record<string, RuleViolations>,
  {
    indentLevel = DEFAULT_INDENT_LEVEL,
    type = 'error',
  }: {
    indentLevel?: number;
    type?: 'error' | 'warning';
  } = {}
): string[] {
  const icons = { error: '❌', warning: '⚠️' };

  return Array.from(Object.entries(rules))
    .sort(sortByFixable)
    .map(
      ([ruleId, [count, isFixable]]) =>
        `${' '.repeat(indentLevel)}"${ruleId}": "off", // ${
          icons[type]
        } ${count} ${type}${count > 1 ? 's' : ''}${isFixable ? ' 🛠️' : ''}`
    );
}

export function getFile(
  ruleDefinitions: {
    files: string[];
    errors: Record<string, RuleViolations>;
    warnings: Record<string, RuleViolations>;
  }[],
  {
    module = 'commonjs',
    indentLevel = DEFAULT_INDENT_LEVEL,
  }: { module: 'commonjs' | 'module' | 'cjs' | 'mjs'; indentLevel?: number }
): string {
  const configTemplate = targetEslintRc(module);
  const intent = ' '.repeat(indentLevel);
  const formattedRules = ruleDefinitions
    .filter(
      ({ errors, warnings }) =>
        Object.values(errors).length > 0 || Object.values(warnings).length > 0
    )
    .map(({ files, errors, warnings }) => {
      const warningLines = formatRules(warnings, { type: 'warning' });
      const errorLines = formatRules(errors);
      const fileLines = JSON.stringify(files).replace(/"/g, "'");
      const errorRules = `\n${intent}// ❌ Errors: ${
        errorLines.length
      }\n${errorLines.join('\n').replace(/"/g, "'")}`;
      const warningRules = `\n${intent}// ⚠️ Warnings: ${
        warningLines.length
      }\n${warningLines.join('\n').replace(/"/g, "'")}`;

      return `{
    files: ${fileLines},
    rules: {${errorLines.length > 0 ? errorRules : ''}${
        warningLines.length > 0 ? warningRules : ''
      }
    },
  },`;
    })
    .join(',\n');

  return configTemplate.replace('<RULES>', formattedRules);
}
